const SELECT_PODCAST_ACTION = 'SELECT_PODCAST_ACTION';
const SELECT_EPISODE_ACTION = 'SELECT_EPISODE_ACTION';
const FLUSH_PODCAST_ACTION = 'FLUSH_PODCAST_ACTION';
const FLUSH_EPISODE_ACTION = 'FLUSH_EPISODE_ACTION';


export {
  SELECT_PODCAST_ACTION,
  SELECT_EPISODE_ACTION,
  FLUSH_PODCAST_ACTION,
  FLUSH_EPISODE_ACTION,
}